services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweqwe
      POSTGRES_DB: postgres
    ports:
      - "5430:5430"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=eureka-server
    networks:
      - app-network

  race-service:
    build:
      context: ./race-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=race-service
    networks:
      - app-network

  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
      - team-service
    environment:
      - SPRING_PROFILES_ACTIVE=driver-service
    networks:
      - app-network

  team-service:
    build:
      context: ./team-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=team-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: