server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/api/games/**
        - id: developer-service
          uri: lb://developer-service
          predicates:
            - Path=/api/developers/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
        - id: userlibrary-service
          uri: lb://userlibrary-service
          predicates:
            - Path=/api/userlibrary/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true